from vue.cadre import *
from controller.controller import *
from controller.ThreadedClient import *

client = ThreadedClient()
client.getGUI().mainloop()
# app = Cadre()
# controller = Controller(app)
# app.mainloop()

# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.CINQ))

# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.AS))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.AS))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.AS))

# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.PIQUE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.DAME))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.AS))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.CINQ))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.AS))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.ROI))
# self.listeCartes.append(Carte(CouleurCarte.CARREAU, ValeurCarte.VALET))
# self.listeCartes.append(Carte(CouleurCarte.TREFLE, ValeurCarte.ROI))
# self.listeCartes.append(Carte(CouleurCarte.COEUR, ValeurCarte.VALET))
